### PR TITLE
Allow config to be passed via env

### LINKED ISSUE #12: feat : allow aws secrets to be passed via environment
Putting aws keys directly in the angular json, accessible to all the devs is like giving them all the secret key.

I think users should be allowed to pass it via env.

### PR DESCRIPTION
**Pull request by beaussart**
Fixes #12

### CODE REVIEW

**Comment by Jefiozie** [comment]
What do  you think of a separate file where you could specify your keys?  See: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-json-file.html

**Comment by beaussart** [comment]
I don't have many time to dedicate to this, if you want to take it, go head! I may have some time next week

**Comment by Jefiozie** [comment]
I will resolve the conflict and the merge it in. Thanks!

**Comment by beaussart** [comment]
I have 5 minutes to resolve the conflict, will do it now :)

**Comment by beaussart** [comment]
Due to a miss click on my part, I closed it. I made another pr with the conflict resolved

**Pull request closed without merging**
