### PR TITLE
fix: remove direct workspace access

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Review by Jefiozie — APPROVED** [review]
LGTM

**Review by Jefiozie — CHANGES_REQUESTED** [review]
Could you update it with the latest changes? 


Thanks, after this we can merge it

**Comment by Jefiozie** [comment]
@all-contributors please add @arturovt for code

**Comment by arturovt** [comment]
@Jefiozie sure, I have rebased the branch.

**Review by Jefiozie — APPROVED** [review]

**Comment by Jefiozie** [comment]
Thank you @arturovt for your contributions. Iwill try and make a release tomorrow.

**Pull request merged**
