### PR TITLE
feat: add multiple configurations set for deploy and fix no-build

### PR DESCRIPTION
**Pull request by Jefiozie**
Still WIP but it should close:
#83 
#170

TODO:

- [ ] add migration schematic for change in configuration
- [ ] add migration schematic tests
- [ ] Document the changes
- [ ] make pre release

### CODE REVIEW

**Comment by cubasepp** [comment]
@Jefiozie can I help you here? 
 
I can need the feature. :) If I can help you please let me know. Thanks

**Comment by Jefiozie** [comment]
Hi @cubasepp thanks for reaching out, I'm thinking of publishing this as a beta. Could you maybe test it for me to see how it works and if you like the new way of configuring? If it works we can continue with the other task and publish it again as a beta until we have a solid set to merge to a final version?

**Comment by cubasepp** [comment]
Hi @Jefiozie of course I will test it for you. Let's do it. 

I look forward to it.

**Comment by cubasepp** [comment]
I will test it tomorrow. Thanks

**Comment by Jefiozie** [comment]
@cubasepp I've just released a version [check it out here](https://www.npmjs.com/package/@jefiozie/ngx-aws-deploy/v/1.3.0-beta.1)

**Comment by Jefiozie** [comment]
Would you mind making issues If you find some? I will add the beta label so that we can focus on this in upcoming period.

**Comment by cubasepp** [comment]
Hey,

@Jefiozie I tested it now and it works perfectly for me. So I will create no Issue.

Thnaks!

**Pull request merged**
